package com.gpt.jpss.sticker;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.gpt.jpss.keycloak.KeycloakUser;
import com.gpt.jpss.sticker.dto.StickerEditRequest;
import com.gpt.jpss.sticker.model.Sticker;
import java.lang.reflect.Field;
import java.time.Instant;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;

/**
 * The rule that matters: a sticker is editable only by the account that placed
 * it. No role grants otherwise, so this is the whole authorization story for
 * writes and it is worth pinning down without a container.
 */
@ExtendWith(MockitoExtension.class)
class StickerServiceTest {

  private static final UUID OWNER = UUID.randomUUID();
  private static final UUID SOMEBODY_ELSE = UUID.randomUUID();

  @Mock private StickerRepository stickers;
  @Mock private StickerImageRepository images;
  @Mock private ImageProcessor imageProcessor;

  @InjectMocks private StickerService service;

  private Sticker sticker;
  private UUID stickerId;

  @BeforeEach
  void setUp() throws Exception {
    var owner = new KeycloakUser(OWNER, "jo", Instant.now());
    sticker = new Sticker(owner, 40.7, -74.0, "hello", null);
    stickerId = UUID.randomUUID();
    setId(sticker, stickerId);
  }

  @Test
  void ownerCanEditTheirOwnSticker() {
    when(stickers.findById(stickerId)).thenReturn(Optional.of(sticker));

    var edited = service.edit(stickerId, OWNER, new StickerEditRequest(48.85, 2.35, "  moved  ", " Paris "));

    assertThat(edited.latitude()).isEqualTo(48.85);
    assertThat(edited.longitude()).isEqualTo(2.35);
    // Trimmed on the way in, so the wall never renders a caption padded with whitespace.
    assertThat(edited.comment()).isEqualTo("moved");
    assertThat(edited.place()).isEqualTo("Paris");
  }

  @Test
  void blankPlaceIsStoredAsAbsent() {
    when(stickers.findById(stickerId)).thenReturn(Optional.of(sticker));

    var edited = service.edit(stickerId, OWNER, new StickerEditRequest(1.0, 2.0, "hi", "   "));

    assertThat(edited.place()).isNull();
  }

  @Test
  void editingSomebodyElsesStickerIsForbidden() {
    when(stickers.findById(stickerId)).thenReturn(Optional.of(sticker));

    assertThatThrownBy(
            () -> service.edit(stickerId, SOMEBODY_ELSE, new StickerEditRequest(1.0, 2.0, "mine now", null)))
        .isInstanceOf(ResponseStatusException.class)
        .extracting(e -> ((ResponseStatusException) e).getStatusCode())
        .isEqualTo(HttpStatus.FORBIDDEN);
  }

  @Test
  void deletingSomebodyElsesStickerIsForbiddenAndRemovesNothing() {
    when(stickers.findById(stickerId)).thenReturn(Optional.of(sticker));

    assertThatThrownBy(() -> service.delete(stickerId, SOMEBODY_ELSE))
        .isInstanceOf(ResponseStatusException.class);

    verify(stickers, never()).delete(any());
    verify(images, never()).deleteById(any());
  }

  @Test
  void deletingYourOwnStickerAlsoRemovesItsBytes() {
    when(stickers.findById(stickerId)).thenReturn(Optional.of(sticker));

    service.delete(stickerId, OWNER);

    // The image is keyed by the sticker id rather than associated to it, so
    // nothing cascades — the service has to remove it, and this is the guard.
    verify(images).deleteById(stickerId);
    verify(stickers).delete(sticker);
  }

  @Test
  void anUnknownStickerIsNotFound() {
    UUID missing = UUID.randomUUID();
    when(stickers.findById(missing)).thenReturn(Optional.empty());

    assertThatThrownBy(() -> service.get(missing))
        .isInstanceOf(ResponseStatusException.class)
        .extracting(e -> ((ResponseStatusException) e).getStatusCode())
        .isEqualTo(HttpStatus.NOT_FOUND);
  }

  /** BaseEntity's id is generated by the persistence provider; tests have to plant one. */
  private static void setId(Sticker sticker, UUID id) throws Exception {
    Field field = sticker.getClass().getSuperclass().getDeclaredField("id");
    field.setAccessible(true);
    field.set(sticker, id);
  }
}
