package com.gpt.jpss.sticker;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.gpt.jpss.keycloak.KeycloakUser;
import com.gpt.jpss.sticker.dto.Caller;
import com.gpt.jpss.sticker.dto.StickerEditRequest;
import com.gpt.jpss.sticker.model.Sticker;
import java.lang.reflect.Field;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;

/**
 * The rule that matters: a sticker is editable only by the account that placed
 * it. No role grants otherwise, so this is the whole authorization story for
 * writes and it is worth pinning down without a container.
 */
@ExtendWith(MockitoExtension.class)
class StickerServiceTest {

  private static final UUID OWNER = UUID.randomUUID();
  private static final UUID SOMEBODY_ELSE = UUID.randomUUID();

  @Mock private StickerRepository stickers;
  @Mock private StickerImageRepository images;
  @Mock private ImageProcessor imageProcessor;

  @InjectMocks private StickerService service;

  private KeycloakUser owner;
  private Sticker sticker;
  private UUID stickerId;

  @BeforeEach
  void setUp() throws Exception {
    owner = new KeycloakUser(OWNER, "jo", Instant.now());
    sticker = new Sticker(owner, 40.7, -74.0, "hello", null);
    stickerId = UUID.randomUUID();
    setId(sticker, stickerId);
  }

  @Test
  void ownerCanEditTheirOwnSticker() {
    when(stickers.findById(stickerId)).thenReturn(Optional.of(sticker));

    var edited = service.edit(stickerId, author(OWNER), new StickerEditRequest(48.85, 2.35, "  moved  ", " Paris "));

    assertThat(edited.latitude()).isEqualTo(48.85);
    assertThat(edited.longitude()).isEqualTo(2.35);
    // Trimmed on the way in, so the wall never renders a caption padded with whitespace.
    assertThat(edited.comment()).isEqualTo("moved");
    assertThat(edited.place()).isEqualTo("Paris");
  }

  @Test
  void blankPlaceIsStoredAsAbsent() {
    when(stickers.findById(stickerId)).thenReturn(Optional.of(sticker));

    var edited = service.edit(stickerId, author(OWNER), new StickerEditRequest(1.0, 2.0, "hi", "   "));

    assertThat(edited.place()).isNull();
  }

  @Test
  void editingSomebodyElsesStickerIsForbidden() {
    when(stickers.findById(stickerId)).thenReturn(Optional.of(sticker));

    assertThatThrownBy(
            () -> service.edit(stickerId, author(SOMEBODY_ELSE), new StickerEditRequest(1.0, 2.0, "mine now", null)))
        .isInstanceOf(ResponseStatusException.class)
        .extracting(e -> ((ResponseStatusException) e).getStatusCode())
        .isEqualTo(HttpStatus.FORBIDDEN);
  }

  @Test
  void deletingSomebodyElsesStickerIsForbiddenAndRemovesNothing() {
    when(stickers.findById(stickerId)).thenReturn(Optional.of(sticker));

    assertThatThrownBy(() -> service.delete(stickerId, author(SOMEBODY_ELSE)))
        .isInstanceOf(ResponseStatusException.class);

    verify(stickers, never()).delete(any());
    verify(images, never()).deleteById(any());
  }

  @Test
  void deletingYourOwnStickerAlsoRemovesItsBytes() {
    when(stickers.findById(stickerId)).thenReturn(Optional.of(sticker));

    service.delete(stickerId, author(OWNER));

    // The image is keyed by the sticker id rather than associated to it, so
    // nothing cascades — the service has to remove it, and this is the guard.
    verify(images).deleteById(stickerId);
    verify(stickers).delete(sticker);
  }

  @Test
  void anUnknownStickerIsNotFound() {
    UUID missing = UUID.randomUUID();
    when(stickers.findById(missing)).thenReturn(Optional.empty());

    assertThatThrownBy(() -> service.get(missing))
        .isInstanceOf(ResponseStatusException.class)
        .extracting(e -> ((ResponseStatusException) e).getStatusCode())
        .isEqualTo(HttpStatus.NOT_FOUND);
  }

  /** BaseEntity's id is generated by the persistence provider; tests have to plant one. */
  private static void setId(Sticker sticker, UUID id) throws Exception {
    Field field = sticker.getClass().getSuperclass().getDeclaredField("id");
    field.setAccessible(true);
    field.set(sticker, id);
  }

  @Test
  void servesTheThumbnailWithoutReadingTheFullSizedBytes() {
    var updated = Instant.parse("2026-09-02T10:00:00Z");
    when(images.findThumbnail(stickerId)).thenReturn(Optional.of(rendition("small".getBytes(), updated)));

    var payload = service.image(stickerId, true);

    assertThat(payload.bytes()).isEqualTo("small".getBytes());
    assertThat(payload.updatedAt()).isEqualTo(updated);
    // The point of the projection: asking for a thumbnail must not touch the
    // row that carries the display rendition too.
    verify(images, never()).findById(any());
    verify(images, never()).findFull(any());
  }

  @Test
  void servesTheDisplayImageForTheDefaultVariant() {
    when(images.findFull(stickerId))
        .thenReturn(Optional.of(rendition("large".getBytes(), Instant.EPOCH)));

    assertThat(service.image(stickerId, false).bytes()).isEqualTo("large".getBytes());
    verify(images, never()).findThumbnail(any());
  }

  @Test
  void reportsAMissingImageAsNotFound() {
    when(images.findFull(stickerId)).thenReturn(Optional.empty());

    assertThatThrownBy(() -> service.image(stickerId, false))
        .isInstanceOf(ResponseStatusException.class)
        .extracting(e -> ((ResponseStatusException) e).getStatusCode())
        .isEqualTo(HttpStatus.NOT_FOUND);
  }

  @Test
  void returnsTheWallNewestFirstWithItsAuthorNames() {
    when(stickers.wall()).thenReturn(List.of(sticker));

    var wall = service.wall();

    assertThat(wall).hasSize(1);
    assertThat(wall.getFirst().authorName()).isEqualTo(sticker.getAuthor().getUsername());
    assertThat(wall.getFirst().id()).isEqualTo(stickerId);
  }

  private static StickerImageRepository.Rendition rendition(byte[] bytes, Instant updatedAt) {
    return new StickerImageRepository.Rendition() {
      @Override
      public byte[] getBytes() {
        return bytes;
      }

      @Override
      public String getContentType() {
        return "image/jpeg";
      }

      @Override
      public Instant getUpdatedAt() {
        return updatedAt;
      }
    };
  }

  @Test
  void letsAModeratorEditSomebodyElsesSticker() {
    when(stickers.findById(stickerId)).thenReturn(Optional.of(sticker));

    var edited = service.edit(
        stickerId, moderator(SOMEBODY_ELSE), new StickerEditRequest(1.0, 2.0, "tidied up", null));

    assertThat(edited.comment()).isEqualTo("tidied up");
    // Moderation fixes and removes; it never reassigns authorship.
    assertThat(edited.authorId()).isEqualTo(OWNER);
    assertThat(edited.authorName()).isEqualTo(sticker.getAuthor().getUsername());
  }

  @Test
  void letsAModeratorDeleteSomebodyElsesSticker() {
    when(stickers.findById(stickerId)).thenReturn(Optional.of(sticker));

    service.delete(stickerId, moderator(SOMEBODY_ELSE));

    verify(stickers).delete(sticker);
    verify(images).deleteById(stickerId);
  }

  @Test
  void stillRefusesANonModeratorWhoIsNotTheAuthor() {
    when(stickers.findById(stickerId)).thenReturn(Optional.of(sticker));

    assertThatThrownBy(() -> service.delete(stickerId, author(SOMEBODY_ELSE)))
        .isInstanceOf(ResponseStatusException.class)
        .extracting(e -> ((ResponseStatusException) e).getStatusCode())
        .isEqualTo(HttpStatus.FORBIDDEN);
  }

  private static Caller author(java.util.UUID id) {
    return new Caller(id, false);
  }

  private static Caller moderator(java.util.UUID id) {
    return new Caller(id, true);
  }

  @Test
  void refusesAnUploadOnceTheCapIsReachedWithoutTouchingTheImage() {
    ReflectionTestUtils.setField(service, "maxPerUser", 3);
    when(stickers.countByAuthorId(OWNER)).thenReturn(3L);

    assertThatThrownBy(() -> service.create(owner, edit(), upload()))
        .isInstanceOf(ResponseStatusException.class)
        .extracting(e -> ((ResponseStatusException) e).getStatusCode())
        .isEqualTo(HttpStatus.TOO_MANY_REQUESTS);

    // The whole point of checking first: a rejected upload must not cost a
    // decode and a re-encode of an 8MB photo.
    verify(imageProcessor, never()).process(any());
    verify(stickers, never()).save(any());
  }

  @Test
  void refusesAnUploadThatBreachesTheRollingWindow() {
    ReflectionTestUtils.setField(service, "perWindow", 5);
    when(stickers.countByAuthorId(OWNER)).thenReturn(1L);
    when(stickers.countByAuthorIdAndCreatedAtAfter(eq(OWNER), any())).thenReturn(5L);

    assertThatThrownBy(() -> service.create(owner, edit(), upload()))
        .isInstanceOf(ResponseStatusException.class)
        .extracting(e -> ((ResponseStatusException) e).getStatusCode())
        .isEqualTo(HttpStatus.TOO_MANY_REQUESTS);

    verify(imageProcessor, never()).process(any());
  }

  @Test
  void allowsAnUploadComfortablyInsideBothLimits() {
    when(stickers.countByAuthorId(OWNER)).thenReturn(2L);
    when(stickers.countByAuthorIdAndCreatedAtAfter(eq(OWNER), any())).thenReturn(1L);
    when(imageProcessor.process(any()))
        .thenReturn(new ImageProcessor.Processed(
            new byte[] {1}, "image/jpeg", 800, 600, new byte[] {2}, "image/jpeg"));
    when(stickers.save(any())).thenAnswer(call -> {
      Sticker saved = call.getArgument(0);
      ReflectionTestUtils.setField(saved, "id", UUID.randomUUID());
      ReflectionTestUtils.setField(saved, "createdAt", Instant.now());
      ReflectionTestUtils.setField(saved, "updatedAt", Instant.now());
      return saved;
    });

    var created = service.create(owner, edit(), upload());

    assertThat(created.authorId()).isEqualTo(OWNER);
    verify(imageProcessor).process(any());
  }

  @Test
  void doesNotRateLimitReplacingThePhotoOnAnExistingSticker() {
    ReflectionTestUtils.setField(service, "maxPerUser", 1);
    when(stickers.findById(stickerId)).thenReturn(Optional.of(sticker));
    when(imageProcessor.process(any()))
        .thenReturn(new ImageProcessor.Processed(
            new byte[] {1}, "image/jpeg", 800, 600, new byte[] {2}, "image/jpeg"));
    when(images.findById(stickerId)).thenReturn(Optional.empty());

    // A replace cannot grow the table, which is what the limit protects.
    service.replaceImage(stickerId, author(OWNER), upload());

    verify(stickers, never()).countByAuthorId(any());
  }

  private static StickerEditRequest edit() {
    return new StickerEditRequest(1.0, 2.0, "hello", "somewhere");
  }

  private static MultipartFile upload() {
    return new MockMultipartFile("image", "p.jpg", "image/jpeg", new byte[] {1, 2, 3});
  }
}
