volumes:
  gpt_bff_postgres_data:

networks:
  gpt-network:
    driver: bridge

services:
  postgres:
    container_name: gpt-bff.pgsql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=secret
      - SPRINGBONK_DB_NAME=gpt-springbonk-db
      - SPRINGBONK_DB_USER=springbonk_user
      - SPRINGBONK_DB_PASSWORD=springbonk_password
      - KEYCLOAK_DB_NAME=gpt-keycloak-db
      - KEYCLOAK_DB_USER=keycloak_user
      - KEYCLOAK_DB_PASSWORD=keycloak_password
    volumes:
      - gpt_bff_postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "gpt-db", "-U", "secret" ]
      interval: 3s
      timeout: 60s
      retries: 20
    networks:
      - gpt-network