#!/bin/bash
set -e

# Create users and databases using environment variables
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create databases
    CREATE DATABASE "$SPRINGBONK_DB_NAME";
    CREATE DATABASE "$KEYCLOAK_DB_NAME";

    -- Create users
    CREATE USER "$SPRINGBONK_DB_USER" WITH PASSWORD '$SPRINGBONK_DB_PASSWORD';
    CREATE USER "$KEYCLOAK_DB_USER" WITH PASSWORD '$KEYCLOAK_DB_PASSWORD';

    -- Grant privileges
    GRANT ALL PRIVILEGES ON DATABASE "$SPRINGBONK_DB_NAME" TO "$SPRINGBONK_DB_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$KEYCLOAK_DB_NAME" TO "$KEYCLOAK_DB_USER";
EOSQL