volumes:
  gpt_bff_postgres_data:

services:
  nginx:
    image: nginx:latest
    container_name: gpt-bff.nginx-reverse-proxy
    ports:
      - "7080:7080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs:ro
      - ./logs:/var/log/nginx
    networks:
      - gpt-network

  postgres:
    container_name: gpt-bff.pgsql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gpt-db
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=secret
      - SPRINGBONK_DB_NAME=gpt-springbonk-db
      - SPRINGBONK_DB_USER=springbonk_user
      - SPRINGBONK_DB_PASSWORD=springbonk_password
      - KEYCLOAK_DB_NAME=gpt-keycloak-db
      - KEYCLOAK_DB_USER=keycloak_user
      - KEYCLOAK_DB_PASSWORD=keycloak_password
    volumes:
      - gpt_bff_postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "gpt-db", "-U", "secret" ]
      interval: 3s
      timeout: 60s
      retries: 20

  keycloak:
    container_name: gpt-bff.auth
    image: quay.io/keycloak/keycloak:24.0.0
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/import/:/opt/keycloak/data/import/
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://gpt-bff.pgsql:5432/gpt-keycloak-db
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_URL: https://localhost:7080/auth
      KC_HOSTNAME_ADMIN_URL: https://localhost:7080/auth
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      #KC_HOSTNAME_DEBUG: true
      KC_HTTP_RELATIVE_PATH: /auth/
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      #KC_LOG_LEVEL: DEBUG
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "LOCALHOST_NAME:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth/health/live' ]
      interval: 5s
      timeout: 5s
      retries: 20

  springbonk:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:5
    env_file:
      - .env
    # A volume thing here for deployed app props? idk.
    networks:
      - gpt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7084/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  gpt-network:
    driver: bridge
