scheme: https

reverse-proxy-container-name: ${KC_HOSTNAME}
reverse-proxy-port: ${KC_PORT}
reverse-proxy-uri: ${scheme}://${reverse-proxy-container-name}:${reverse-proxy-port}

authorization-server-prefix: /auth
issuer: ${reverse-proxy-uri}${authorization-server-prefix}/realms/gpt-keycloak
client-id: gpt-keycloak-confidential
client-secret: ${KEYCLOAK_CLIENT_SECRET}  # Add this to .env file
username-claim-json-path: $.preferred_username
authorities-json-path: $.realm_access.roles

bff-port: ${SPRING_BFF_PORT}
bff-prefix: /bff

resource-server-container-name: gpt-bff.spring-resource
resource-server-port: ${SPRING_RESOURCE_PORT}

audience:

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

server:
  port: ${bff-port}

spring:
  security:
    oauth2:
      client:
        provider:
          gpt-keycloak:
            issuer-uri: ${issuer}
        registration:
          gpt-keycloak:
            provider: gpt-keycloak
            authorization-grant-type: authorization_code
            client-id: ${client-id}
            client-secret: ${client-secret}
            scope: openid,profile,email,offline_access
  cloud:
    gateway:
      routes:
        - id: bff
          uri: ${scheme}://${resource-server-container-name}:${resource-server-port}
          predicates:
            - Path=/api/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay=
            - SaveSession
            - StripPrefix=1

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${issuer}
            authorities:
              - path: ${authorities-json-path}
            aud: ${audience}
        client:
          client-uri: ${reverse-proxy-uri}${bff-prefix}
          security-matchers:
            - /api/**
            - /login/**
            - /oauth2/**
            - /logout
          permit-all:
            - /api/**
            - /login/**
            - /oauth2/**
          csrf: cookie-accessible-from-js
          oauth2-redirections:
            rp-initiated-logout: ACCEPTED
        resourceserver:
          permit-all:
            - /login-options
            - /error
            - /actuator/health
            - /actuator/health/readiness
            - /actuator/health/liveness