# Base #############################################################################################
resource-scheme: ${SCHEME_RESOURCE_SERVER:https}
resource-container-name: ${CONTAINER_NAME_RESOURCE:localhost}
resource-prefix: ${PREFIX_RESOURCE:/api}
# Reverse Proxy ####################################################################################
reverse-proxy-scheme: ${SCHEME_REVERSE_PROXY:https}
reverse-proxy-port: ${PORT_REVERSE_PROXY:7080}
reverse-proxy-container-name: ${CONTAINER_NAME_REVERSE_PROXY:localhost}
reverse-proxy-uri: ${reverse-proxy-scheme}://${reverse-proxy-container-name}:${reverse-proxy-port}
# Authorization Server #############################################################################
auth-server-prefix: ${PREFIX_AUTH:/auth}
auth-server-issuer: ${AUTH_ISSUER:/realms/local-keycloak}
auth-server-jwk-set: ${AUTH_JWK_SET:/protocol/openid-connect/certs}
issuer: ${reverse-proxy-uri}${auth-server-prefix}${auth-server-issuer}
jwk-set: ${issuer}${auth-server-jwk-set}
# Server Properties ################################################################################
server:
  port: ${PORT_RESOURCE_SERVER:7084}
# Spring Properties ################################################################################
spring:
  application:
    name: SpringBonk
  devtools:
    add-properties: ${DEV_TOOLS_ADD_PROPS:false}
    livereload:
      enabled: ${DEV_TOOLS_LIVE_RELOAD:false}
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${RESOURCE_DATASOURCE_URL}
    username: ${RESOURCE_DATASOURCE_USERNAME}
    password: ${RESOURCE_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  doc:
    swagger-ui:
      # MARK # TODO: Swagger requires a functional OAUTH implementation.
      enabled: false
# Spring OIDC Properties ###########################################################################
com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${issuer}
            username-claim: ${AUTH_USERNAME_CLAIM_JSON:$.preferred_username}
            authorities:
              - path: ${AUTH_AUTHORITIES_JSON:$.realm_access.roles}
            aud: ${AUTH_AUDIENCE:}
        resourceserver:
          permit-all:
            - /user/details
            - /swagger-ui*/**
            - /v3/api-docs*/**
            - /actuator/health/readiness
            - /actuator/health/liveness
# Log Levels #######################################################################################
logging:
  level:
    org:
      keycloak: INFO
# Actuator
#management:
#  endpoint:
#    health:
#      probes:
#        enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  health:
#    livenessstate:
#      enabled: true
#    readinessstate:
#      enabled: true