# Base #############################################################################################
resource-scheme: ${SCHEME_RESOURCE_SERVER:https}
resource-container-name: ${CONTAINER_NAME_RESOURCE:localhost}
resource-prefix: ${PREFIX_RESOURCE:/api}
# Reverse Proxy ####################################################################################
reverse-proxy-scheme: ${SCHEME_REVERSE_PROXY:https}
reverse-proxy-port: ${PORT_REVERSE_PROXY:7080}
reverse-proxy-container-name: ${CONTAINER_NAME_REVERSE_PROXY:localhost}
reverse-proxy-uri: ${reverse-proxy-scheme}://${reverse-proxy-container-name}:${reverse-proxy-port}
# Authorization Server #############################################################################
auth-server-prefix: ${PREFIX_AUTH:/auth}
auth-server-issuer: ${AUTH_ISSUER:/realms/gpt-keycloak}
auth-server-jwk-set: ${AUTH_JWK_SET:/protocol/openid-connect/certs}
issuer: ${reverse-proxy-uri}${auth-server-prefix}${auth-server-issuer}
jwk-set: ${issuer}${auth-server-jwk-set}
# Application Properties ###########################################################################
server:
  port: ${PORT_RESOURCE_SERVER:7084}

spring:
  application:
    name: SpringBonk
  devtools:
    add-properties: ${DEV_TOOLS_ADD_PROPS:false}
    livereload:
      enabled:  ${DEV_TOOLS_LIVE_RELOAD:false}
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${RESOURCE_DATASOURCE_URL}
    username: ${RESOURCE_DATASOURCE_USERNAME}
    password: ${RESOURCE_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  doc:
    swagger-ui:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer}
          jwk-set-uri: ${jwk-set}

logging:
  level:
    org:
      keycloak: INFO